# Generated by Django 5.1.7 on 2025-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug-example', unique=True),
            preserve_default=False,
        ),
    ]
